/* AUTHENTICATION */
// Register
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";
// Login
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
// Check sessions
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";
// Logout
export const AUTH_LOGOUT = "AUTH_LOGOUT";
/* STORE */
// register store
export const STORE_REGISTER = "STORE_REGISTER";
export const STORE_REGISTER_SUCCESS = "STORE_REGISTER_SUCCESS";
export const STORE_REGISTER_FAILURE = "STORE_REGISTER_FAILURE";
// get all stores (admin)
export const GET_ALL_STORES = "GET_ALL_STORES";
export const GET_ALL_STORES_SUCCESS = "GET_ALL_STORES_SUCCESS";
export const GET_ALL_STORES_FAILURE = "GET_ALL_STORES_FAILURE";
// edit store
export const EDIT_STORE = "EDIT_STORE";
export const EDIT_STORE_SUCCESS = "EDIT_STORE_SUCCESS";
export const EDIT_STORE_FAILURE = "EDIT_STORE_FAILURE";
// get one store
export const GET_ONE_STORE = "GET_ONE_STORE";
export const GET_ONE_STORE_SUCCESS = "GET_ONE_STORE_SUCCESS";
export const GET_ONE_STORE_FAILURE = "GET_ONE_STORE_FAILURE";
// delete store
export const DELETE_STORE = "DELETE_STORE";
export const DELETE_STORE_SUCCESS = "DELETE_STORE_SUCCESS";
export const DELETE_STORE_FAILURE = "DELETE_STORE_FAILURE";
// get store from distance
export const GET_STORE_DISTANCE = "GET_STORE_DISTANCE";
export const GET_STORE_DISTANCE_SUCCESS = "GET_STORE_DISTANCE_SUCCESS";
export const GET_STORE_DISTANCE_FAILURE = "GET_STORE_DISTANCE_FAILURE";
